config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources:events do
      resources:rsvps
  end

  authenticated :user do
  root to: 'events#index', as: :authenticated_root
end
root to: 'home#land'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :rsvps
  belongs_to :user
   validates :user,presence:true
def self.pretty_new
  ev = self.new
  ev_time = Time.now.beginning_of_hour()+ 1.hour
  ev.start_time = ev_time
  ev.end_time = ev_time + 1.hour

  return ev

end

def single_day?
  start_time.to_date == end_time.to_date
end

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  belongs_to :event
  validates:email, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :confirmable,:database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action:authenticate_user!

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

protected

def parse_time(resource_sym,attr)
  time_params = []
  (1..5).each do |counter|
    time_params.push(params[resource_sym]["#{attr}(#{counter}i)"].to_i)
  end
  DateTime.new(time_params[0],time_params[1],time_params[2],time_params[3],time_params[4])

end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :fetch_event, only: [:edit,:update,:destroy]

  def new
    @event = Event.pretty_new

  end

  def create
    @event = current_user.events.new(event_params)
    # @event.title = params[:event][:title]
    # @event.description = params[:event][:description]
    @event.start_time = parse_time(:event,"start_time")
    @event.end_time = parse_time(:event,"end_time")
    # @event.start_time = DateTime.new(params[:event]["start_time(1i)"].to_i,
    # params[:event]["start_time(2i)"].to_i,params[:event]["start_time(3i)"].to_i,
    # params[:event]["start_time(4i)"].to_i,params[:event]["start_time(5i)"].to_i)
    # @event.end_time = DateTime.new(params[:event]["end_time(1i)"].to_i,
    # params[:event]["end_time(2i)"].to_i,params[:event]["end_time(3i)"].to_i,
    # params[:event]["end_time(4i)"].to_i,params[:event]["end_time(5i)"].to_i)
    @event.save
    redirect_to events_path
  end

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @rsvps = @event.rsvps.all
    @new_rsvp = @event.rsvps.new
  end

  def edit
    # fetch_event
  end

  def update
    # fetch_event
    set_start_and_end_time
    @event.update_attributes(event_params)
    @event.save
    redirect_to @event

  end

  def destroy
    @event.destroy
    redirect_to events_path
  end


private
  def event_params
      params.require(:event).permit(:title,:description)
  end

def set_start_and_end_time
  @event.start_time = parse_time(:event,"start_time")
  @event.end_time = parse_time(:event,"end_time")
end

def fetch_event
  @event = current_user.events.find(params[:id])
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter:authenticate_user!
  def land

  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  def create
    @event =Event.find(params[:event_id])
    @rsvp = @event.rsvps.new
    @rsvp.email = params[:rsvp][:email]
    flash[:alert] = "Please enter your email" unless @rsvp.save


    redirect_to @event
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_tag(msg, msg_type)
    return unless msg.present?
    if msg_type == "notice"
      msg_type = "info"
    elsif msg_type == "alert"
      msg_type = "danger"
    end

    content_tag(:div, class: "alert alert-#{msg_type} alert-dismissible", role: "alert") do
      button_tag(class: "close", "data-dismiss" => "alert") do
        content_tag(:span, raw("&times;"), "aria-hidden" => true) +
          content_tag(:span, "Close", class: "sr-only")
      end + msg
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper

  def event_time_tag(event)

     if event.single_day?

        # <div class="common_date">
        #   <h3><%= @event.start_time.strftime("%b %-d, %Y") %></h3>
        #   <p>
        #     <%= @event.start_time.strftime("%l:%M %P") %> - <%= @event.end_time.strftime("%l:%M %P") %>
        #   </p>
        # </div>
      #  content_tag(:div,"sadasdsadsad", class: "common_date")
          content_tag(:div,class:"common_date") do
            content_tag(:h3,event.start_time.strftime("%b %-d, %Y")) +
              content_tag(:p,"#{event.start_time.strftime("%l:%M %P")} to #{event.end_time.strftime("%l:%M %P")}")
          end
     else
        # <div class="diff_date">
        #   <h3><%= @event.start_time.strftime("%b %-d, %Y  %l:%M %P") %></h3>
        #   <p>
        #     to
        #   </p>
        #   <h3><%= @event.end_time.strftime("%b %-d, %Y  %l:%M %P") %></h3>
        # </div>
        content_tag(:div,class:"diff_date") do
          content_tag(:h3,event.start_time.strftime("%b %-d, %Y  %l:%M %P")) +
            content_tag(:p,"to")+
              content_tag(:h3,event.end_time.strftime("%b %-d, %Y  %l:%M %P"))
        end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/common/_header.html.erb
<header>
      <nav class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
              <%= link_to "Eventify", root_path, class:"navbar-brand" %>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in?  %>
                <li><%= link_to "Add Event",new_event_path %></li>
                <li><%= link_to "Browse Events", events_path %></li>

              <!-- <li><a href="<%= new_event_path%>">Add Event</a></li>
              <li><a href="<%= events_path%>">Browse Events</a></li> -->
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                  <li class="divider"></li>
                  <li><%= link_to "Logout",destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
              <% else %>
              <li><%= link_to "Login",new_user_session_path %></li>
              <li><%= link_to "Signup",new_user_registration_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>

</header>

app/views/events/_event.html.erb
<div class="event well">
    <%= link_to "Details", event_path(event), class:"pull-right" %>
    <% if event.user == current_user  %>
    <%= link_to "Edit", edit_event_path(event), class:"pull-right" %>
    <%= link_to "Delete", event_path(event),method: :delete, class:"pull-right" %>
    <% end %>
    <h3><%= event.title %></h3>
    <p>
      <%= event.description %>
    </p>
</div>

app/views/events/_form.html.erb
<%= simple_form_for event, html:{class:'well'} do |f| %>
<%= f.input:title %>
<%= f.input:description %>
<%= f.input:start_time %>
<%= f.input:end_time %>
<%= f.submit (event.new_record? ? 'Add Event' : 'Update Event'), class:'btn btn-primary btn-lg' %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event:<%= @event.title  %></h1>

<%= render partial: "events/form", locals: {event: @event} %>

app/views/events/index.html.erb
<h1>Events</h1>
<section id="events">
 <% if @events.any? %>
                              <% if false  %>
                              <ul>
                              <% @events.each do |event| %>
                                <%= render partial:"events/event" ,locals: {event: event} -%>
                                <%= render event %>
                              <% end %>
                              <% end  %>

    <%= render @events  %>
<%else  %>
  <div class="well">
     No Events yet
  </div>
<%end  %>
</ul>
</section>

app/views/events/new.html.erb
<h1>Create a new Event</h1>

<%= simple_form_for @event, html:{class:'well'} do |f| %>
<%= f.input:title %>
<%= f.input:description %>
<%= f.input:start_time %>
<%= f.input:end_time %>
<%= f.submit:'Add Event', class:'btn btn-primary btn-lg' %>
<% end %>

app/views/events/show.html.erb
<section id="event" class ="container-fluid">

  <div class="row">
    <div class="col-sm-9">
      <% if @event.user == current_user  %>
      <%= link_to "Edit", edit_event_path(@event), class:"pull-right" %>
      <%= link_to "Delete", event_path(@event),method: :delete, class:"pull-right" %>
      <% end %>
      <h1><%= @event.title %></h1>
      <p><%= @event.description %></p>

    </div>
    <div class="col-sm-3 ">
          <div class="well">
              <%= event_time_tag(@event) %>
          </div>
          <div class="well">
              <h2>Attendees</h2>
              <%= simple_form_for [@event,@new_rsvp] do |f| %>
                <%= f.input:email, label:false , placeholder: "Enter your email" %>
                <%= f.submit:'I want to Attend', class:"btn btn-sm btn-primary btn-block"%>
              <%end%>
              <ul>
              <%= render @rsvps %>
              </ul>
          </div>
    </div>
  </div>

</section>

app/views/home/land.html.erb
<h1>Welcome!</h1>
<h2>1 and 4 make <%= 1+4 %></h2>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventify</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "common/header" %>
<div class="container">
    <div class="flash_message">
      <%= flash_tag(notice,"notice") %>
      <%= flash_tag(alert,"alert") %>
    </div>
    <%= yield %>
</div>

</body>
</html>

app/views/rsvps/_rsvp.html.erb
<li><%= rsvp.email %></li>